# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :initial_build do
    cocoapods
    carthage
    
    get_provisioning_profile
    gym(
      workspace: "e-sleep.xcworkspace",
      configuration: "Debug",
      scheme: "e-sleep_dev",
      silent: true
    )
  end

  lane :build do
    get_provisioning_profile
    gym(
      workspace: "e-sleep.xcworkspace",
      configuration: "Debug",
      scheme: "e-sleep_dev",
      silent: true
    )
  end

  lane :release do
    gym(workspace: "e-sleep.xcworkspace", scheme: "e-sleep")
    upload_to_app_store
  end
end
